const productsData = [
    {
      "name": "Laptop Pro",
      "description": "A high-performance laptop for professionals.",
      "price": 1299.99,
      "category": "Electronics",
      "stock_quantity": 30,
      "manufacturer": "TechGear",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Smart TV 4K",
      "description": "A 55-inch 4K Ultra HD Smart TV.",
      "price": 699.99,
      "category": "Electronics",
      "stock_quantity": 20,
      "manufacturer": "ElectroVision",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Coffee Maker",
      "description": "A programmable coffee maker for your morning brew.",
      "price": 49.99,
      "category": "Kitchen Appliances",
      "stock_quantity": 15,
      "manufacturer": "BrewMaster",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Bluetooth Speaker",
      "description": "Portable Bluetooth speaker with stereo sound.",
      "price": 79.99,
      "category": "Electronics",
      "stock_quantity": 40,
      "manufacturer": "AudioHub",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Running Shoes",
      "description": "High-performance running shoes for athletes.",
      "price": 99.99,
      "category": "Sports & Outdoors",
      "stock_quantity": 25,
      "manufacturer": "AthleticCo",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Desk Chair",
      "description": "Ergonomic office chair for comfortable work.",
      "price": 199.99,
      "category": "Furniture",
      "stock_quantity": 10,
      "manufacturer": "ComfortZone",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Cookware Set",
      "description": "A complete set of non-stick cookware for your kitchen.",
      "price": 149.99,
      "category": "Kitchen Appliances",
      "stock_quantity": 12,
      "manufacturer": "CookMaster",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Dumbbell Set",
      "description": "Adjustable dumbbell set for home workouts.",
      "price": 149.99,
      "category": "Sports & Outdoors",
      "stock_quantity": 18,
      "manufacturer": "FitGear",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Tablet X",
      "description": "10-inch tablet with powerful performance.",
      "price": 199.99,
      "category": "Electronics",
      "stock_quantity": 22,
      "manufacturer": "TechSolutions",
      "created_at": { $currentDate: { type: "date" } },
    },
    {
      "name": "Blender Pro",
      "description": "Professional-grade blender for smoothies and more.",
      "price": 129.99,
      "category": "Kitchen Appliances",
      "stock_quantity": 14,
      "manufacturer": "BlendMaster",
      "created_at": { $currentDate: { type: "date" } },
    },
  ];
  
  db.products.insertMany(productsData)
  